@startuml 
skinparam style strictuml
[*] --> Borne_disponible 
state Borne_disponible : Do(set_dispo(ON))
Borne_disponible -->Attente_prise : [charge]
state Attente_prise : Do(set_charge(ROUGE)), Do(Deverouille_trappe()) \n Do(tension(12V)), Do(set_dispo(OFF))

Attente_prise --> Prise_branchée : [DC 9V]
state Prise_branchée :  Do(set_charge(VERT)), Do(verouille_trappe())\n  Do(generer_AC(1kHz))

Prise_branchée --> Attente_S2_Vehicule : [AC 9V]
state Attente_S2_Vehicule : Do(generer_AC())
Prise_branchée --> Batterie_chargée :Entered(STOP)

Attente_S2_Vehicule --> Charge  : [AC 6V]
state Charge : Do(fermer_AC())\n Do(generer_PWM(+6V/-12V))
Attente_S2_Vehicule --> Batterie_chargée : Entered(STOP)
Charge --> Batterie_chargée : [AC 9V] ou Entered(STOP)
state Batterie_chargée : Do(arret_PWM()), Do(set_charge(VERT))
Batterie_chargée --> retrait_prise : [deconnecter] 
state retrait_prise :  Do(ouvrir_contacteur_AC())\n Do(déverouiller())

retrait_prise --> prise_debranché : [12V]
state prise_debranché : Do(set_charge(OFF), \n set_prise(OFF) set_dispo(ON))

prise_debranché --> [*] 
@enduml
